### ISSUE TITLE
Selecting "Rail Only" in Trip Planning Doesn't Return Light Rail Trips

### ISSUE THREAD

**Issue by devinbraun** [OneBusAway/onebusaway-android#1035]
**Summary:** 

When planning a trip, if a user selects "Rail Only", light rail results are not returned, but might be expected by the user.

**Steps to reproduce:** 

Create a trip plan using the Transit Only option which includes light rail or "Tram" in OTP parlance.  Then switch the additional trip options to Rail Only.  If there are no heavy rail options for the trip plan, light rail isn't returned and no trip plan is possible.

**Expected behavior:** 

The app should show light rail when selecting "Rail Only"

**Device and Android version:** 

Model: Pixel 2
OS Version: 10 / 29

**Comment by devinbraun** [comment]
The available travel options for San Diego are here:
http://realtime.sdmts.com:9090/otp/routers

This trip plan with modes of "RAIL/WALK" doesn't produce any results:
[](https://realtime.sdmts.com:9091/otp/routers/default/plan?date=04-22-2020&mode=RAIL,WALK&arriveBy=false&wheelchair=false&optimize=QUICK&showIntermediateStops=true&fromPlace=32.7525,-117.147&toPlace=32.5697,-117.066&maxWalkDistance=1609.265467845169&time=02:30PM )

There are "modes" and "travel options" as available URL parameters.  Perhaps this is a case where travelOptions of BUS, TRAM or RAIL should be used rather than modes?  The following trip plan works
[](https://realtime.sdmts.com:9091/otp/routers/default/plan?date=04-22-2020&arriveBy=false&wheelchair=false&optimize=QUICK&showIntermediateStops=true&fromPlace=32.7525,-117.147&toPlace=32.5697,-117.066&maxWalkDistance=1609.265467845169&time=02:30PM&travelOptions=Rail,Tram)

**Comment by barbeau** [comment]
@devinbraun Thanks for reporting this! I agree, it would make sense to return light rail trips when the user selects "Rail".

Do you know what the GTFS routes.txt `route_type` is for these light rail routes?

**Comment by barbeau** [comment]
Here's a sample "Rail only" request used in OBA Android for San Diego:
https://realtime.sdmts.com:9091/otp/routers/default/plan?date=04-23-2020&mode=RAIL,WALK&arriveBy=false&wheelchair=false&optimize=QUICK&showIntermediateStops=true&fromPlace=32.9580,-117.126&toPlace=33.1216,-117.320&time=11:51AM

**Comment by devinbraun** [comment]
Light rail is route_type = 0 in San Diego's GTFS

**Comment by barbeau** [comment]
Looking at the OTP REST API docs:
http://dev.opentripplanner.org/apidoc/1.4.0/resource_PlannerResource.html

`mode` is defined as:

>The set of modes that a user is willing to use, with qualifiers stating whether vehicles should be parked, rented, etc.

A `travelOptions` parameter isn't listed there as a valid parameter, though - I'm not sure what that is defined for or used as. I think we're seeing TRAM results in the sample request just because we aren't restricting `mode` to RAIL. For example, if I remove the `travelOptions` parameter from the request I believe I see the same results:
https://realtime.sdmts.com:9091/otp/routers/default/plan?date=04-22-2020&arriveBy=false&wheelchair=false&optimize=QUICK&showIntermediateStops=true&fromPlace=32.7541,-117.136&toPlace=32.5697,-117.066&maxWalkDistance=1609.265467845169&time=02:30PM

route_type 0 in GTFS (https://gtfs.org/reference/static#routestxt) is defined as:

>Tram, Streetcar, Light rail. Any light rail or street level system within a metropolitan area.

...so it would make sense for this to map to the `TRAM` mode in OTP.

But, I don't get any results when I add `TRAM` to the `mode` parameter, which would be the most obvious solution:
https://realtime.sdmts.com:9091/otp/routers/default/plan?date=04-22-2020&mode=RAIL,TRAM,WALK&arriveBy=false&wheelchair=false&optimize=QUICK&showIntermediateStops=true&fromPlace=32.7541,-117.136&toPlace=32.5697,-117.066&maxWalkDistance=1609.265467845169&time=02:30PM

@devinbraun Could you confirm that the above lat/longs for origin and destination are for a trip you could take only using light rail (i.e., not requiring any transfers to bus)? For example, just from one light rail station to another?

**Comment by devinbraun** [comment]
Here's one that works for TRAM,WALK, but not for RAIL,WALK as it is between two stations served by light rail with no easy bus connections:

https://realtime.sdmts.com:9091/otp/routers/default/plan?date=04-22-2020&mode=TRAM,WALK&arriveBy=false&wheelchair=false&optimize=QUICK&showIntermediateStops=true&fromPlace=32.70562,-117.153180&toPlace=32.804663,-116.976180&maxWalkDistance=1609.265467845169&time=02:30PM

**Comment by barbeau** [comment]
Ok, nice! And it looks like you get the same result if you include RAIL as well as TRAM:
https://realtime.sdmts.com:9091/otp/routers/default/plan?date=04-22-2020&mode=RAIL,TRAM,WALK&arriveBy=false&wheelchair=false&optimize=QUICK&showIntermediateStops=true&fromPlace=32.70562,-117.153180&toPlace=32.804663,-116.976180&maxWalkDistance=1609.265467845169&time=02:30PM

So it looks like the solution, then, is for the "Rail only" option to use the modes `RAIL,TRAM,WALK`.

Does that sound right to you, @devinbraun?

**Comment by devinbraun** [comment]
I think it's safe to use both RAIL and TRAM.  It would be an issue where we have heavy rail and light rail overlap.  The NCTD COASTER train is in our GTFS files and it shares a few stations with the light rail.  It sounds like users would get both options and would need to select between the heavy rail or light rail options if shown but I think most users would understand getting both types of trains if they selected Rail Only.

**Comment by barbeau** [comment]
@devinbraun I've just pushed a new beta, v2.7.1, that has this fix. Could you please give it a try and see if the light rail trips show up now?

**Comment by devinbraun** [comment]
@barbeau Yes, it works fine now.  I get light rail trips when selecting "Rail only".

**Comment by barbeau** [comment]
@devinbraun Awesome, thanks for testing!
