### ISSUE TITLE
Fix the case with overlapping map stops

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#15]
We should be able to detect stops that are right on top of each other, or close enough within some range, and popup something that will allow you to disambiguate them.

**Comment by bbodenmiller** [comment]
I think this would be better off at a API level than in each app.

**Comment by barbeau** [comment]
Yeah, this should really be fixed in the configuration of the bundle-building phase when deploying data with an OBA server.  It can either be done with a manual mapping (e.g., and semi-automated using something like this tool we created for Tampa Bay - https://github.com/CUTR-at-USF/onebusaway-stop-consolidation-support), or via an automated process if there are a lot of automated stops - see https://groups.google.com/forum/#!topic/onebusaway-developers/FvOOav_C9D4 for a discussion of how this works for Sound Transit.  These are much better approaches to fixing the problem, and I haven't actually seen this happen since I've been maintaining the app (so maybe this is already fixed server-side in all regions?) so I'm going to close this out as "Won't fix" for now.  If it pops up again we can revisit.
