### ISSUE TITLE
Improve issue reporting

### ISSUE THREAD

**Issue by cagryInside** [OneBusAway/onebusaway-android#187]
Summary:  To provide some background – in Tampa, HART has gotten a large amount of feedback from transit riders via OneBusAway.  However, they lack good infrastructure to triage/manage these issues, both because of the multi-departmental administration of OBA, as well as issues that cross jurisdictions and may not relate to HART infrastructure.  Therefore, cross-departmental and cross-agency communication on issues is very important.
 
Our group at USF is looking to improve this process with better support for open issue reporting and tools to triage/manage issues.  We are also working to on-board another regional agency, PSTA that serves Pinellas County, into OneBusAway Tampa.
 
Our current plan is to:
 
1.       Improve the current help/feedback process within the app – Right now, there are several channels within the app to seek help/report problems.  A) Users can report trip/stop problem reports within the arrivals screen.  However, it is not easily discoverable.  B) Users can send an email C) A Twitter account for the region is accessible.  We’d like to better organize/present this within the app so we direct the user to the best channel to submit their feedback based on the type of feedback.
2.       Direct infrastructure/agency-specific feedback to dedicated issue reporting sites – HART has indicated that it is difficult for them to process email and stop problem reports within the OBA webapp.  Therefore, we’d like to provide the option for a region to direct their infrastructure-specific and general feedback (basically, anything not related to arrival times) via established issue reporting sites (more detail below).
 
For 2, we plan to leverage some of the open issue reporting frameworks that already exist, such as [Open311]( http://www.open311.org/).  There are a number of Open311-compliant reporting sites such as [SeeClicFix.com]( http://seeclickfix.com/) (which [Pinellas County is already using]( http://seeclickfix.com/pinellas_county)) – or, regions could set up their own Open311 server.  Use of these 3rd party issue reporting sites would be option for each region (if you want to use it, provide the URL of the Open311 service you want to use in the OBA Directory.  If not, leave it blank).  This optional component will be similar in nature to the StopInfo project.
 
TODO:
·         Add open311 server URL to OBA Server Directory
·         Validate region before submitting report
·         Implement (or leverage existing) open311 client
·         Investigate/Implement backend integration with open311 service

**Comment by barbeau** [comment]
Another item I'd like to add to this is to provide an option for "Ideas for new features", or some similar wording, that would direct the user to the OneBusAway Android Ideascale page:
http://onebusaway.ideascale.com/a/ideas/top/campaign-filter/byids/campaigns/46167

**Comment by barbeau** [comment]
@cagryInside Could you please open a WIP PR with the enhanced issue reporting that we've been working on?  No rush, but I'd like to get it into a PR so others can monitor progress as well.  It's fine if you need to rebase/force push to that WIP PR as you continue to update/work on things.

**Comment by cagryInside** [comment]
@barbeau sure. I will open a WIP PR soon.

**Comment by cagryInside** [comment]
I opened the PR for this implementation: PR https://github.com/OneBusAway/onebusaway-android/pull/255.

**Comment by barbeau** [comment]
We recently found out that Manatee County, which would also be covered by OBA Tampa, is using PublicStuff as their issue reporting vendor:
https://www.mymanatee.org/home/contact-us-form/publicstuff-request.html

This is in addition to Pinellas and potentially HART using SeeClickFix:
http://seeclickfix.com/pinellas_county

So, it looks like we need to design to support more than one Open311 API endpoint per region. 

Regions API would include something like the following for each region:

~~~
open311baseUrls: [
{
baseUrl = "http://first.endpoint.com"
},
{
baseUrl = "http://second.endpoint.com"
}
],
~~~

And, we'd need to figure out discovery for each endpoint to know which one is active when someone is reporting an issue for a given lat/long.

Option A is the way we're doing discovery now for SeeClickFix Open311 API, which is to see if only one "Other" category is returned for a lat/long - however, we'd need to make sure something similar is possible for PublicStuff's Open311 API (because discovery is technically outside of the Open311 standard).  Then, we'd query each endpoint to see which ones were operational in the area (should only be one active endpoint per lat/long).  

Option B is to define a geographic bounds for each API endpoint and include that info in the Regions API response.

I'd prefer Option A, because it doesn't require us updating the geographic endpoints in the Regions API.  Ultimately, I don't think Option B is sustainable or scalable for several, or even one, region.  Different areas could be added or removed in the backend issue reporting system, and unless the vendor keeps us up to date (not likely to happen) we'd have no way of knowing this occurred.

**Comment by bbodenmiller** [comment]
I'm not completely up to speed on this issue however keep in mind that certain agencies overlap. For example in Puget Sound, many agencies operate within the City of Seattle.

**Comment by barbeau** [comment]
@bbodenmiller True!  In the case of issue reporting, though, we're typically talking about a government entity (usually county or city) signing up for a commercial service like SeeClickFix or PublicStuff.  In the cases we've seen so far, this requires coordination with other overlapping jurisdictions - otherwise a citizen doesn't ultimately know where to report a problem too.  For example, Pinellas County started with SeeClickFix, and then onboarded the City of St. Pete, local transit agency (both within the county), and the parent FDOT district.  The big benefit to this type of system is that the citizen doesn't need to understand overlapping jurisdictional boundaries - they just report an issue with a category to the system, and it gets routed behind the scenes to the appropriate jurisdiction/department based on location and issue type.  

There may end up being situations where issue reporting systems overlap, but I think this will be the exception, and likely a temporary situation until better coordination takes place - it really doesn't make sense financially or operationally to have overlapping issue reporting services.  My comment above should handle the case where there are several non-overlapping issue reporting services covered by the same OBA region.  For example, if an OBA region covers multiple counties and each county signs up for a different (non-overlapping) issue reporting service (which will likely be our case in Tampa), we'd be able to direct the issue accordingly.

**Comment by barbeau** [comment]
Another feature we need to support is submitting general feedback to a customer service-specific email address.  For example, the "my bus driver was rude" and "lost and found" feedback needs to go to straight customer service, not the department managing OneBusAway.

I think this customer feedback email address will need to be per-transit agency (i.e., we'll have several per region), so the best place for it to live is likely in the GTFS data.  Unfortunately there currently is no `agency_email` field in [agency.txt](https://developers.google.com/transit/gtfs/reference?hl=en#agencytxt) (there is `agency_phone` and `agency_url`).  If we can get some of the OBA agencies to start adding this to their GTFS data, and we expose it in the OBA REST API responses references section and consume it in the apps, then we should be able to get this field added to the GTFS spec.

**Comment by barbeau** [comment]
@cagryInside Could you put together another screenshot that looks like [this](https://cloud.githubusercontent.com/assets/2777974/7334217/7428e992-eb5b-11e4-886c-8a4cd3bf74d6.png), but includes a new "customer service" feedback category too?

I'd like to be able to show this to Sound Transit and HART on Thurs.

Let's put it on the top, with the title:

>Contact Customer Service

...and the subtitle:
>Driver compliments and complaints, lost & found, etc.

This would probably lead to another screen to "Select your transit agency", which would have the list of supported agencies (same as "Help->Supported Agencies" now).  Upon selecting the agency, it would open an email to that agency's customer service email address (this would most likely come from GTFS data and be a field in the ObaAgency class).

**Comment by bbodenmiller** [comment]
Do you know if there is any situations where an agency wouldn't have a feedback email but rather only a feedback website?

**Comment by barbeau** [comment]
@bbodenmiller It's possible - in that case, I suppose we'd direct them to GTFS agency.txt `agency_url`.  Or, a new GTFS agency.txt `customer_service_url` that doesn't exist yet, if `agency_url` doesn't work (it may not).  We'd need to see what the real-world scenarios are for the current OBA agencies.

**Comment by barbeau** [comment]
Here's the screenshot that @cagryInside put together that includes a customer service element:

![image](https://cloud.githubusercontent.com/assets/928045/9915584/dcb6a54e-5c85-11e5-9a80-f03c2ae91604.png)

**Comment by barbeau** [comment]
After talking with HART, Puget Sound, and ARC, we're going to make phone call or email an option for the "Contact Customer Service".  In GTFS, `agency_phone` already exists in `agency.txt`, so we can pull that from the existing GTFS data, as long as the agency populates it.

**Comment by bbodenmiller** [comment]
In the example given at https://github.com/OneBusAway/onebusaway-iphone/issues/518 of a user wanting to report an early departure how should one go about that as it could mean many things? For example, it could mean the bus departed before OBA said it would (based on bad schedule or real-time data) or it could just be that the user wants to report it as leaving early which is against agency policy but OBA had correct data.

**Comment by barbeau** [comment]
For reference, here are the current most popular issue categories that are reported via the OBA trip/stop problem reporting APIs.

Puget Sound:

~~~
mysql> SELECT code, COUNT(*) FROM oba_trip_problem_reports GROUP BY code ORDER BY COUNT(*) DESC;
+----------------------------+----------+
| code                       | COUNT(*) |
+----------------------------+----------+
| vehicle_never_came         |    59513 |
| vehicle_came_late          |    18768 |
| vehicle_came_early         |     5944 |
| other                      |     3229 |
| NULL                       |     1066 |
| vehicle_does_not_stop_here |      521 |
| wrong_headsign             |      126 |
+----------------------------+----------+
7 rows in set (1.55 sec)

mysql> 
mysql> SELECT code, COUNT(*) FROM oba_stop_problem_reports GROUP BY code ORDER BY COUNT(*) DESC;
+-----------------------+----------+
| code                  | COUNT(*) |
+-----------------------+----------+
| other                 |     1038 |
| route_or_trip_missing |      656 |
| stop_name_wrong       |      465 |
| NULL                  |      186 |
| stop_location_wrong   |      111 |
| stop_number_wrong     |       24 |
+-----------------------+----------+
6 rows in set (0.01 sec)
~~~
Tampa (just for HART):

![image](https://cloud.githubusercontent.com/assets/928045/14385891/970093c0-fd70-11e5-9538-041cb8f81012.png)

Atlanta:

~~~
org_onebusaway_database=# SELECT code, COUNT(*) FROM oba_trip_problem_reports GROUP BY code ORDER BY COUNT(*) DESC;
            code            | count 
----------------------------+-------
 vehicle_came_late          |   197
 vehicle_never_came         |   132
 vehicle_came_early         |    58
                            |    19
 other                      |    18
 vehicle_does_not_stop_here |     4
 wrong_headsign             |     3
(7 rows)

org_onebusaway_database=# SELECT code, COUNT(*) FROM oba_stop_problem_reports GROUP BY code ORDER BY COUNT(*) DESC;
         code          | count 
-----------------------+-------
 other                 |    14
 route_or_trip_missing |     8
 stop_name_wrong       |     5
                       |     4
 stop_location_wrong   |     2
~~~
