### ISSUE TITLE
More Google Analytics - donate link & opt-out

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#213]
Just realized that we should be tracking taps on "Donate" preference.

@cagryInside Would you be able to put this together tomorrow?

My goal is to get a new beta based on the master branch that includes GA out by the end of this week.

**Comment by cagryInside** [comment]
@barbeau Yes, I can open a PR for tomorrow. 
Moreover, what do you think about this https://github.com/OneBusAway/onebusaway-android/pull/212#issuecomment-75638517. We might want to log when the user disables the analytics.

**Comment by barbeau** [comment]
@cagryInside Yes, I think its reasonable to detect the opt-out itself.  I just changed the name of this ticket to reflect that as well, so you can submit in the same PR.

**Comment by cagryInside** [comment]
### NOTE:
Google analytics' ```setAppOptOut()``` method removed for enabling/disabling the GA in the app. Because, when we send event before disabling the GA, the event doesn't show up in the GA admin. This issues also posted to stackoverflow:
http://stackoverflow.com/q/28688695/701325
http://stackoverflow.com/q/28701628/701325

Instead of using ```setAppOptOut()```, a workaround solution implemented. Simply before pushing any log to GA, we check if the GA is active in the app.
