### ISSUE TITLE
Trip planning

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#25]
There's no longer an OBA API for it, but people continue to ask for it. Frankly I doubt I will ever have time to do this, but I want to keep something open because it's such a popular feature request.

To be clear, this would involve either bringing back Brian's API, integrating OpenTripPlanner, or running my own server. If it were a different server it would have to be kept updated with GTFS updates just like the main OBA server is.

Moved from: http://code.google.com/p/seattle-bus-bot/issues/detail?id=83

**Comment by barbeau** [comment]
@sheldonabrown This is the official ticket for trip planning on OBA Android.  Just wanted to tag you so you received any updates here.

**Comment by barbeau** [comment]
I've started some work on fleshing out how this may fit into the current OBA UI navigation flow.  Here's the branch:
https://github.com/OneBusAway/onebusaway-android/tree/25-tripPlan

Basically, this adds another navigation drawer option that opens to a new activity where the trip planning UI would start:

![image](https://cloud.githubusercontent.com/assets/928045/10115602/6e958f32-63db-11e5-89ec-9d788282d53e.png)

**Comment by barbeau** [comment]
Some mockups for the possible look of the trip planning activity flow follow.

First trip planning screen is on the left - user taps on the "Plan My Trip" button, and sees the initial results screen shown on the right:

![image](https://cloud.githubusercontent.com/assets/928045/10144553/4bf4d3e4-65ec-11e5-9a1f-d9e648621ab1.png)

By tapping on the map icon in the upper right-hand corner, the user can see the same trip results on the map:

![image](https://cloud.githubusercontent.com/assets/928045/10144595/822600be-65ec-11e5-86d9-2686c70504b2.png)

Note that this could be reversed as well so that the map-based results show up first.

Here's a sample "Advanced search" options screen, that the user would see when tapping on the menu of the initial origin/destination screen menu:

![image](https://cloud.githubusercontent.com/assets/928045/10144656/b8da3bde-65ec-11e5-8ab9-85c0d32ad8a0.png)

**Comment by barbeau** [comment]
HART asked about a feature that would alert users when a bus is delayed and provide alternate trip plans, AFTER a user has already planned their trip.

We have something similar in OTP Android - here's how it works:
* User plans a trip (based on real-time info, if that's available in the OTP server)
* Within 1 hr of the estimated departure time, OTP Android starts re-querying the server for updated estimates that effect that trip every minute
* If the estimated arrival time changes, the user is notified, and can tap on the notification to re-plan their trip

The discussion of the implementation of this feature starts around this comment in OTP Android:
https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/issues/21#issuecomment-50652181

...and this should be the PR that added the feature:
https://github.com/CUTR-at-USF/OpenTripPlanner-for-Android/pull/306

Here are some screenshots of the notification, and how real-time info looks in context of the trip plan in OTP Android:

![image](https://cloud.githubusercontent.com/assets/928045/10166413/e2b4fa02-6691-11e5-876e-409488a80af2.png)

**Comment by barbeau** [comment]
York's current implementation is slightly different that the original mockups they provided in terms of content/style - the best way to see what the current app looks like is to sign up for their beta updates here - https://play.google.com/apps/testing/can.yrt.onebusaway.

**Comment by barbeau** [comment]
@sheldonabrown Ok, I've rebased the below branch on master as of today (currently v2.0.9):
https://github.com/OneBusAway/onebusaway-android/tree/25-tripPlan

This adds the new "Plan a trip" option to the navigation drawer as shown in https://github.com/OneBusAway/onebusaway-android/issues/25#issuecomment-143394440, and when tapping on this it launches a new activity.  The new activity is currently just a hello world shell, and you can drop in the York or OTP Android activity implementations there.  Let me know if you have any questions!

**Comment by barbeau** [comment]
WIP PR at https://github.com/OneBusAway/onebusaway-android/pull/541.

**Comment by barbeau** [comment]
Squashed/rebased PR at https://github.com/OneBusAway/onebusaway-android/pull/602.
