### ISSUE TITLE
Back button in Preferences Action Bar does not go to home screen

### ISSUE THREAD

**Issue by kurtraschke** [OneBusAway/onebusaway-android#258]
From the Preferences screen, tapping the green "< OneBusAway" button in the header does nothing.  Tapping the system back button in the footer goes back to the previous screen as expected.

OneBusAway 1.7.8, HTC One M8, Android 5.0.1

**Comment by barbeau** [comment]
Thanks Kurt.  IIRC, most of the action bar "up" navigation is broken (or at least doesn't behave according to the Google design standards) in the current OBA Android version on Google Play (v1.7.8).

I've been working on a UI overhaul that includes replacing the ActionBar implementation, which is currently in the `develop` branch - you can download an APK for this if you'd like from a link in the top post of #177.  Up navigation in the preferences Action Bar is still missing in this branch (it was fixed briefly, until Google changed the behavior of this in the newest version of the support libraries), but it will be fixed in the final version.

I'll leave this ticket open as a reminder that it still needs to be fixed in develop.

**Comment by barbeau** [comment]
For posterity sake, here's the Google design guidelines outlining the difference between "up" and "back" navigation:
http://developer.android.com/design/patterns/navigation.html

Tapping on the "<-" button in the ActionBar should initiate the "up" navigation.

**Comment by barbeau** [comment]
Fixed in `develop` branch via https://github.com/OneBusAway/onebusaway-android/commit/d60ce77ba4e4f604a662df67a40d28ec6f71cac4.
