### ISSUE TITLE
Location used when not needed

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#366]
Appears a few screens are continuing to use my location when not needed, so far that includes:

* starred stops
* my reminders

**Comment by barbeau** [comment]
So this is an unfortunate side-effect of the way we have to implement fragment switching in the main activity when using the map.  The map has to remain active in the background (i.e., hidden and not removed), otherwise we lose the map state and have to re-initialize it when switching back to the "Nearby" screen - this reinit is horrible UX.

If you switch to either "Starred stops" or "My reminders", and then kill and restart the app so it starts with one of these screens instead of "Nearby", then location shouldn't be in use, because the map fragment isn't initialized yet.  But, once you switch to the "Nearby" screen, then the map is initialized and location is active and continues to be active until onPause() of HomeActivity is called (when you leave the app or go to another activity that's not using your location).

I'm going to mark this as "won't fix" for now because its an implementation limitation, but let me know if you see different behavior from the above.

**Comment by bbodenmiller** [comment]
Thanks for the explanation. It does appear that if I force it to start on a screen other than nearby it's not using my location. Additionally I checked Google Maps and it appears to suffer from the same issue.
