### ISSUE TITLE
Support upgrading from release to alpha to develop releases

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#386]
Currently I've got the alpha version of OBA installed from the Play Store. Upon attempting to deploy latest from master branch from my machine to phone I'm getting `INSTALL_FAILED_UPDATE_INCOMPATIBLE` & `INSTALL_FAILED_CONFLICTING_PROVIDER` errors. Would be great to go from released versions to dev versions without losing all data.

**Comment by barbeau** [comment]
This would be nice but unfortunately won't work.  We sign release builds with our release keys (which are private), and development builds are signed using the keys bundled with the Git repo (onebusaway-android/seattlebusbot3.debug.keystore).  In Android you can only replace/upgrade an app signed with the same cert, otherwise you have to uninstall and re-install.

A workaround is to save your data to storage in settings, and then just restore after switching.  Android Studio should handle the uninstall of the Play release and install of master automatically now (this used to fail - now it prompts you and asks if this is ok), so its not too big a deal.

**Comment by bbodenmiller** [comment]
Is there anything that could be done to improve the process however? For example can the two apps share a data store? Can the build setup automatically give the develop build a different identifier so as to not conflict with releases from the play store? Could the app automatically backup? What about prompt that a backup is available to restore from on initial run?

If these are possibly I could look in to them but would appreciate any guidance you might have.

**Comment by barbeau** [comment]
>Can the build setup automatically give the develop build a different identifier so as to not conflict with releases from the play store?

Yes, we could allow the side-by-side installation of the development and release builds by changing the package identifier (i.e., `com.joulespersecond.seattlebusbot`) for the development build.  They would essentially function as two separate apps in that case.  I believe this would be done in `build.gradle` as part of the build flavor config, although I haven't had a chance to look into it.

>What about prompt that a backup is available to restore from on initial run?

This might work - our local "backups" are essentially writing the local database to storage.  Off the top of my head I don't know if there would be any conflicts trying to read the file that was written to external storage by an app with a different signature.  See `RestorePreference` and `SavePreference` classes for how this is implemented.  I wouldn't want this to conflict with us configuring the real Auto-Backup, though, so we need to think that through.
