### ISSUE TITLE
Restoring an old database version results in empty Open311 tables

### ISSUE THREAD

**Issue by cagryInside** [OneBusAway/onebusaway-android#478]
**Summary:** 

If you get a backup of DB with the lower version of the application, and restore this DB after you upgrade the application, it will effectively delete the data in new created tables.

**Steps to reproduce:** 

1. Download the lower version of the app. 
1. Go to settings and click `Save to storage`. 
1. Remove the app. 
1. Download the latest version of the app. 
1. Go to settings and click `Restore from storage`. 

The latest version of the app has `Open311 url` data in the tables. After you do the above operations, the Open311 servers table will be empty.

***Shortcut steps to reproduce:*** 
Download the latest version of the app. Download [db.backup.zip](https://github.com/OneBusAway/onebusaway-android/files/247113/db.backup.zip) (taken from an older version of OBA) and unzip it. Put it under `\Internal storage\OBABackups`. Go to Settings and click `Restore from storage`. 

**Expected behavior:** 

It should update the data in the old tables. If there is new table, it repopulate it if possible.

**Observed behavior:** 

When you restore an older version of DB, the Open311 servers table will be empty. 

**Device and Android version:** 

Stock Nexus 6 w/ Android 6.0.1 I don't believe this is device or version specific bug. It can occur with any device or version.

**Screenshots:** 

Before DB dump It has open 311 enpoint:
![device-2016-05-03-105933](https://cloud.githubusercontent.com/assets/2777974/14987657/683c91d0-111e-11e6-827c-bba61d895731.png)

After DB dump, the open311 endpoints are no longer in the DB:
![device-2016-05-03-110110](https://cloud.githubusercontent.com/assets/2777974/14987666/6fef89be-111e-11e6-891a-cdd9b65eb2db.png)

**Comment by barbeau** [comment]
This is a side effect of our current backup method, which is simply to copy the database file to storage in https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/java/org/onebusaway/android/io/backup/Backup.java#L54.  When we "restore" old data, we swap the old database back in.  If the database version changed prior to the fix for https://github.com/OneBusAway/onebusaway-android/issues/473, the app would crash as the platform would trigger `SQLiteOpenHelper.onDowngrade()`, which we weren't handling (the platform natively throws an exception if you don't override `SQLiteOpenHelper.onDowngrade()` to prevent potential data corruption).

In https://github.com/OneBusAway/onebusaway-android/commit/eb058abd0c63d69c0c0143dca5deaf048ad6eb46, we fixed the crash by gracefully handling the `SQLiteOpenHelper.onDowngrade()` and running all the SQL statements to bring the old database schema up to date with the latest schema (i.e., run all the "create" and "update" statements).  While this creates any new tables after `SQLiteOpenHelper.onDowngrade()`, it doesn't populate them.  This results in the empty database tables we're seeing in this issue.

The workaround for this for tables automatically populated from the Regions API like the Open311 servers table is to force a refresh of the Regions API contents after the user restores the database.  We currently do something similar after `SQLiteOpenHelper.onUpgrade()` to make sure that the tables are filled when the user updates the app, and the update contains new tables.

In the future, we'll need to be careful about tables that might be bootstrapped with user data that can't be automatically filled via a Regions API refresh.  In this case, we'd need to re-ask the user for the initial data they provided to re-initialize the tables.

The proper fix for this issue, and potential future issues related to backup/restore and the database version changing, is to implement a real backup/restore mechanism that exports/imports the data without copying the entire database file.
