### ISSUE TITLE
Send feedback Open311 form - move issue category above issue description?

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#519]
**Summary:** 

When reporting an issue via "Send feedback" form, and stop or arrival time problem, it seems like it may be a more natural flow to pick the issue category and then enter a description.  It also helps the user focus on the types of issues they should be reporting here.  I took a look at the Pinellas County (i.e., SeeClickFix white label) app and then put category above issue description.

**Steps to reproduce:** 

1. In main navigation drawer, tap on "Send feedback"
1. Pick "Report a Stop Problem"
1. Tap on a stop in Pinellas County (where there is Open311 coverage).

**Expected behavior:** 

Issue category should appear above the text box to enter an issue description.

**Observed behavior:** 

Issue description is above issue category:

![image](https://cloud.githubusercontent.com/assets/928045/15584273/dc00aeb8-2347-11e6-8ac9-2ef90a028484.png)

**Device and Android version:** 

Stock LG G4 w/ Android 6.0

**Screenshots:** 

See above.

**Comment by barbeau** [comment]
@cagryInside Thoughts on this?  I think the description was above the category in the initial implementation because we use description for both Open311 and non-Open311.  Do you think it causes implementation issues if we try to move the category above the description?

**Comment by cagryInside** [comment]
> @cagryInside Thoughts on this? I think the description was above the category in the initial implementation because we use description for both Open311 and non-Open311. Do you think it causes implementation issues if we try to move the category above the description?

I agree, SCF also puts the description bottom:

![screen shot 2016-05-26 at 4 14 54 pm](https://cloud.githubusercontent.com/assets/2777974/15588711/27a39690-235d-11e6-9e14-94606c49a091.png)

It won't cause any implementation issues, because non-open311 issues have their own `fragments`. 
However, there are other questions coming from the open311 endpoint. So, we will have to add the description and image fields at the end of the open311 questions.
