### ISSUE TITLE
On restore from storage Custom Server API is deleted

### ISSUE THREAD

**Issue by themonki** [OneBusAway/onebusaway-android#536]
**Summary:** 

When save data and restore them, the Custom OBA Server API is removed.

**Steps to reproduce:** 
1. Set a Custom Server API
2. Click on Save to storage
3. Click on Restore from storage
4. Close and Open the App

**Expected behavior:** 

Reload backed up data, and the Custom OBA Server API should still be selected

**Observed behavior:** 

The Custom OBA Server API is deleted and it shows "**the manual region prompt**"

**Device and Android version:** 

Xperia Z3 Compact (D5803)
Manufacturer Sony 
Android version Android 6.0.1
RAM (MB) 2048 
Screen size 720 × 1280 
Screen density (dpi) 320 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8974AC
Google Play Services 9.0.83
EDIT Onebusaway Android version 2.0.13

**Screenshots:** 

none

Edit: in black

**Comment by barbeau** [comment]
@themonki Thanks for the report!

I can reproduce this issue (LG G4 Android 6.0 w/ `master` branch at https://github.com/OneBusAway/onebusaway-android/commit/6efc57548d1dcdb299355176f6db63847569ccd5), but what I see is a little different.  After tapping "Restore", I see the manual region prompt (instead of "Out of range"):

![image](https://cloud.githubusercontent.com/assets/928045/15970544/19523e46-2f03-11e6-99ea-0dc3bbe57eb3.png)

This is very likely an unintended side-effect of https://github.com/OneBusAway/onebusaway-android/pull/528.  There was a past issue (#478) where if you restored an old version of the database, new tables ended up empty.  https://github.com/OneBusAway/onebusaway-android/pull/528 fixes this by running the regions update `ObaRegionsTask` after executing the restore to make sure those tables are populated.

It looks like that when that `AsyncTask` is executed, the part of that task that selects the current region is interfering with the custom server API.  I'll have to dig in a bit deeper to see what the exact cause/fix is.

**Comment by themonki** [comment]
I review this again and Custom OBA Server API is not delete, hurra! 

But when I **Click on Restore** from storage still show the "**Choose region**" dialog, but if you close and reopen the app work with the custom API.

Maybe some dialog say "Please reopen the app"?.

I will close it because it is fixed for the current version.

**Comment by barbeau** [comment]
@themonki Well, that's good! :)  I'll open a separate issue for the "Choose region" dialog.

**Comment by barbeau** [comment]
New issue for "choose region" dialog at https://github.com/OneBusAway/onebusaway-android/issues/781.
