### ISSUE TITLE
Trip planning - Real-time data isn't shown for trips that haven't started yet

### ISSUE THREAD

**Issue by sdjacobs** [OneBusAway/onebusaway-android#606]
**Summary:** 

Trip planning will not have real time information for trips that are not active yet.

This is a server-side issue, though I don't know whether the problem should be fixed in OTP or in the GTFS-RT [source](http://realtime.prod.obahart.org:8088/trip-updates?debug=true). OTP only adds GTFS-RT trip updates to the time tables for the trip they directly refer to -- there is no propagation of block delays to future trips. Either OTP should add interpolation, or the GTFS-RT source should provide more trip predictions. I am not sure which direction is best.

**Steps to reproduce:** 

Plan an itinerary that originates from a terminus with a start time of now. (This ensures that the trip that's returned won't be active yet. This also happens very frequently during planning without doing anything special, because it's often the case that the trip OTP suggests hasn't started yet).

**Expected behavior:** 

Nearly all trips should have real-time data.

**Observed behavior:** 

Trips often don't have real-time data.

**Device and Android version:** 

N/A

**Comment by barbeau** [comment]
@sdjacobs Thanks for opening this issue.  

On a related note, I recall at one point OTP requiring `stop_time_updates` for all stops on a trip in order to apply the update - in other words, if any predictions for stops were missing from a trip, instead of interpolating the missing values.  They called this a "strict" interpretation of the spec,  Is this still the case, or would OTP intepolate missing predictions within the same trip?

For HART, I imagine that this would manifest as real-time updates only showing up if the stop_id/stop_sequence in the GTFS-rt feed matches the stop_id that you plan the trip for.

**Comment by barbeau** [comment]
I'm wrong above - it would manifest as no real-time info for that entire trip, which doesn't seem to be happening - so it's probably no longer an issue.

**Comment by barbeau** [comment]
The more I think about this, the more I'm convinced that modification to the server OTP code is the proper fix for this.  We can't always assume that we'll be able to modify the source real-time feed, and downstream propagation of predictions should occur according to the GTFS-rt spec.  See this related issue for OTP server - https://github.com/opentripplanner/OpenTripPlanner/issues/2295.

**Comment by barbeau** [comment]
I've also changed the status of this issue from "Enhancement" to "Bug", as I believe that best describes the current OTP server behavior.

**Comment by barbeau** [comment]
It should also be noted that the above OTP server issue is currently slated for a v1.0.0 release milestone.

**Comment by abyrd** [comment]
@barbeau we had a tentative design principle for work in the Netherlands that realtime prediction and propagation were to be done in a separate module from OTP. We didn't want a lot of fuzzy, subjective code buried in the OTP code base. Our opinion was that prediction and propagation could only be done accurately by a system with large archives of past performance data, which we thought should be in a separate project/repo when it came to be. So the notion of "strict" feeds was one of using GTFS-RT as an unambiguous internal interface between components, a way to state that a particular feed was to be considered "broken" if it contained any ambiguity or missing values. In practice I believe we're now propagating delays, and the "strict" GTFS-RT concept was never really implemented.

Since no "OTP RT predictor module" project has materialized, I'd agree with you @barbeau that we can't count on having clear, complete RT data. 

However, @sdjacobs I'm not sure I fully understand what this issue is about. You say that "OTP only adds GTFS-RT trip updates to the time tables for the trip they directly refer to -- there is no propagation of block delays to future trips". Does this issue only affect trips that are part of blocks, where the delay message references an earlier trip in the block? Or are you saying that RT messages that reference a specific trip in the future will not be applied to that trip, even when it's not part of a block?

**Comment by abyrd** [comment]
BTW thanks @barbeau for updating milestones, labels, etc. I'd like to get more people working on issue triage!

**Comment by sdjacobs** [comment]
RT updates that reference a trip will have no effect on future trips that share the same block. Other systems, for example OBA, propagate delays downstream.

For example, in the OTP test GTFS feed [testagency.zip](https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/test/resources/testagency.zip), trips `6.1` and `7.1` both have block `block.1`. See `stop_times.txt` restricted to those trips:

<pre>
trip_id,arrival_time,departure_time,stop_id,stop_sequence,shape_dist_traveled,pickup_type,drop_off_type
6.1,12:00:00,12:00:00,I,1,,0,0
6.1,12:10:00,12:10:00,J,2,,0,0
7.1,12:20:00,12:20:00,J,1,,0,0
7.1,12:30:00,12:30:00,K,2,,0,0
</pre>

If we get an update that trip 6.1 is running 15 minutes late, that delay should be propagated to trip 7.1. Since blocks are a sequence of trips on the same vehicle, it's pretty unlikely that 7.1 will depart stop 1 at 12:20!

I'm interested in adding block propagation to OTP but I'm not sure yet if/when I'll have availability. And it would be great to get some guidance on how you'd like to get this feature integrated into the current scheme.

**Comment by sheldonabrown** [comment]
Cambridge Systematics has implemented this and submitted a PR:

https://github.com/opentripplanner/OpenTripPlanner/pull/3176

It's deployed to HART now @barbeau if you'd like to test.

**Comment by barbeau** [comment]
@sheldonabrown Ooo, nice! Thanks for the heads up, I'll take a look. I'll go ahead and close this and will re-open if something doesn't look right.
