### ISSUE TITLE
Home screen shortcuts are erased after reboot on Samsung devices

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#764]
**Summary:** 

Reported by user with Samsung Galaxy S6:

>Widgets all disappear whenever the phone is booted. This is 100% reproducible. The problem occurs with both ways of creating the widgets (long pressing on Starred Stop, or long pressing on Home screen). I mostly use the Stop widget, but I've also tried Route, Recent Routes, Recent Stops,  and Starred Stops and all disappear on a reboot. Only the OneBus widgets disappear, other apps widgets are OK. There are no problems with adding them. 

**Steps to reproduce:** 

On certain Samsung devices:

1. Star a stop
1. Go to "Starred Stops" view, long press on a stop, and choose "Create a shortcut on home screen"
1. Return to home screen and verify shortcut is there
1. Reboot phone

**Expected behavior:** 

Shortcut should still exist after rebooting the device

**Observed behavior:** 

Shortcut disappears after reboot

**Device and Android version:** 

~~~
App Version: 2.1.4
Model: SM-G920V
OS Version: 6.0.1 / 23
Google Play Services App: 10.0.84 (440-137749526)
Google Play Services Library: 9452000
Region/API: Puget Sound (selected automatically)
Loc: network , 27 second(s) ago
~~~

**Comment by barbeau** [comment]
I'm not sure if there is anything we can do about this, but the user did say that the below open-source apps don't have the same problem (i.e., the shortcuts survive a reboot).  So, we could try to look at these and figure out what the different is with OBA:

Forecastie
https://play.google.com/store/apps/details?id=com.casticalabs.forecastie

Ministocks
https://play.google.com/store/apps/details?id=nitezh.ministock

Mirakel
https://play.google.com/store/apps/details?id=de.azapps.mirakelandroid

**Comment by barbeau** [comment]
I'm guessing that this was a device-specific bug, so I'm going to close this to clean up issues.  If anyone is still experiencing this please let me know.

**Comment by bmander** [comment]
Closing as resolved by the shortcuts rewrite.

This bug was in the legacy homescreen-shortcut mechanism (the in-Activity `CREATE_SHORTCUT` picker / `ACTION_INSTALL_SHORTCUT`), which on some Samsung devices didn't survive a reboot. That mechanism has been removed. Shortcuts are now:

- **Static app shortcuts** declared in `res/xml/shortcuts.xml` (OS-managed, inherently persistent), and
- **Pinned shortcuts** via `ShortcutManagerCompat.requestPinShortcut` (`ui/common/Shortcuts.kt`), which the launcher persists across reboots/updates by design.

The manifest also keeps `activity-alias` entries for the frozen legacy component names so any *old* pinned shortcuts still resolve to `HomeActivity`. The reboot/update-erasure described here is no longer possible on the current mechanism. If a persistence problem is ever seen with the modern pinned shortcuts, that would be a fresh, separately-scoped bug.
