### ISSUE TITLE
Trip planning - Can't plan using fully manually entered address

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#778]
**Summary:** 

When planning a trip, if you fully enter an address into the "From:" or "To:" box and then hit enter on the keyboard, nothing happens.  It should geocode the location and proceed with planning the trip.

The workaround (which apparently nearly all users do) is to tap on the address that comes up in the autocomplete drop down box.

Without looking at the code I'm not sure if this is intended behavior from the Google autocomplete widget or a bug on our end.

**Steps to reproduce:** 

1. Tap "Plan a trip" in main navigation drawer
1. Tap "To:" box
1. Enter a full address like "4202 E. Fowler Ave Tampa FL 33620"
1. Tap enter on keyboard

**Expected behavior:** 

Geocode the entered address and finish the trip plan, as if I had tapped on the address in the autocomplete box

**Observed behavior:** 

The keyboard disappears when you hit enter, and you are left staring at the text you typed into the box and the entry in the autocomplete field.

![image](https://user-images.githubusercontent.com/928045/27451568-6d6ca646-575d-11e7-9efb-6e8400ef9c3a.png)

**Device and Android version:** 

LG G5 w/ Android 7.0 w/ Google Play Services App: 11.0.55 (440-156917137)

**Comment by hayato1234** [comment]
Hello, I'm new here and trying to get started with this project with "your first PR".

I looked into the documentation, and it looks like the the widget is design to choose a place from a search list. So, entering an address and hitting enter will show suggestion list even if there is only one suggested place. I think this is intended behavior since onActivityResult is only called when a place is selected.

One way to make this clear might be using PlaceAutocomplete.MODE_FULLSCREEN mode instead of MODE_OVERLAY (Google map uses mode_fullscreen). But if users like current style, it might not be worth changing.

(search with mode_fullscreen as an example)
<img src="https://user-images.githubusercontent.com/19863426/33156507-2b3698d4-cfaf-11e7-99eb-e47fbc04ec02.png" width="300">

**Comment by barbeau** [comment]
Thanks for looking at this @hayato1234! 

Yes, we might just close this as "won't fix" if there isn't any way to configure the widget (e.g., to pick the first option on list on enter) . I think putting it in full sceen mode might just make things more confusing at this point. Interestingly, if you look at the Google Maps behavior it does support hitting enter to search whatever is in the box without picking anything from the list.

**Comment by barbeau** [comment]
I'm closing as "Won't fix" as I only got a single report for this issue and it's a function of the widget we're using.
