### ISSUE TITLE
Arrival time Open311 problem reporting is broken in Tampa

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#982]
**Summary:** 

Reported by a user and I've confirmed - if you try to submit a problem report it gives a toast saying "Required questions should be answered" even if you've filled out all the fields.

**Steps to reproduce:** 

1. Tap on a stop
1. Tap on an arrival time and select "Report an arrival time problem"
1. Fill out all the fields provided

**Expected behavior:** 

Accept the problem report

**Observed behavior:** 

It gives a toast saying "Required questions should be answered" even if you've filled out all the fields

**Device and Android version:** 

Samsung Galaxy S8+ with Android 9.0

**Comment by barbeau** [comment]
An update - I was able to get a stop problem report to submit successfully, so it looks like this issue may be specific to arrival time problem reports

**Comment by cagryInside** [comment]
@barbeau I find the problem.  In the application, we weren't able to show one required field:

![device-2019-05-27-152336](https://user-images.githubusercontent.com/2777974/58436483-99c6c800-8093-11e9-8821-bddd324cbad5.png)

That was because we weren't handling the `text` datatype.  There are existing 6 datatypes defined by Open311 (i.e., `string, number, datetime, text, singlevaluelist, multivaluelist`). In the OBA we were handling all but `text` datatype. Therefore, the application wasn't showing the required field marked in the image above.  

I will create a PR shortly and the issue will be fixed in the next release.  However, if we want a quick fix, we can request to change the `text` datatype to `string` for the marked field.
